seed: 1

type: render

data:
  image_size: [256, 256]

renderer:
  type: sphere_tracing
  chunk_size: 8192
  near: 0.0
  far: 5.0
  max_iters: 64

sampler:
  type: stratified
  n_pts_per_ray:
  min_depth:
  max_depth:

implicit_function:
  type: sdf_surface
  
  sdf:
    type: complex_scene
    sun:
      center: { val: [0.0, 0.0, 0.0], opt: True }
      radius: { val: 1.0, opt: False }
    planet1:
      center: { val: [3.0, 0.0, 0.0], opt: True }
      radius: { val: 0.5, opt: False }
    planet2:
      center: { val: [-4.0, 0.0, 0.0], opt: True }
      radius: { val: 0.7, opt: False }
    orbit1:
      center: { val: [0.0, 0.0, 0.0], opt: False }
      radii: { val: [3.0, 0.05], opt: False }
    orbit2:
      center: { val: [0.0, 0.0, 0.0], opt: False }
      radii: { val: [4.0, 0.05], opt: False }
    satellite:
      center: { val: [3.5, 0.5, 0.0], opt: True }
      side_lengths: { val: [0.2, 0.2, 0.2], opt: False }

  feature:
    rainbow: True
    val: [1.0, 1.0, 1.0]
    opt: False